### ISSUE TITLE
CRUD de Cidade e Estado

### ISSUE THREAD

**Issue by DouglasMonteles** [UnBArqDsw2022-1/2022.1_G3_Bazar_Backend#1]
## Descrição da Issue
Implementação do CRUD de Estado e Cidade que estão se relacionando por composição

## Tasks:
- [x] Implementação das classes de modelo (Java beans)
- [x] Mapeamento Objeto-Relacional com JPA e Hibernate
- [x] Repository, Service e Controller de Cidade
- [x] Repository, Service e Controller de Estado
