### ISSUE TITLE
Autenticação e Autorização com JWT

### ISSUE THREAD

**Issue by DouglasMonteles** [UnBArqDsw2022-1/2022.1_G3_Bazar_Backend#6]
## Descrição da Issue
Implementação da funcionalidade de autenticação e autorização com Spring Security e Oauth

## Tasks:
- [ ] Classes modelo (Usuario e Papel)
- [ ] Mapeamento Objeto-Relacional 
- [ ] Classes de configuração
- [ ] Repository e Service de autenticação
